{
  jsonnet_bin_image: 'eu.gcr.io/unicorn-985/docker-images_jsonnet:v1',
  helm_action_image: 'docker://europe-docker.pkg.dev/gynzy-test-project/public-images/helm-action:v2',
  mysql_action_image: 'docker://europe-docker.pkg.dev/gynzy-test-project/public-images/mysql-action:v1',
  docker_action_image: 'docker://europe-docker.pkg.dev/gynzy-test-project/public-images/push-to-gcr-github-action:v1',
  default_job_image: 'alpine:3.18.3',
  default_mysql57_image: 'eu.gcr.io/unicorn-985/docker-images_mysql57_utf8mb4:v1',
  default_mysql8_image: 'eu.gcr.io/unicorn-985/docker-images_mysql8_utf8mb4:v1',
  default_cloudsql_image: 'eu.gcr.io/unicorn-985/docker-images_cloudsql-sidecar:v1',
  default_redis_image: 'redis:5.0.6',
  default_unicorns_image: 'node:18.15',
  default_pubsub_image: 'messagebird/gcloud-pubsub-emulator:latest',
  default_backend_nest_image: 'node:18.15',
  default_mongodb_image: 'eu.gcr.io/unicorn-985/docker-images_mongo6-replicated:v1',
  mongo_action_image: 'docker://europe-docker.pkg.dev/gynzy-test-project/public-images/action-mongo-cloner:v1',
  default_python_image: 'python:3.11.4',
}
