{
  jsonnet_bin_image: 'europe-docker.pkg.dev/unicorn-985/private-images/docker-images_jsonnet:v1',
  helm_action_image: 'docker://europe-docker.pkg.dev/gynzy-test-project/public-images/helm-action:v2',
  mysql_action_image: 'docker://europe-docker.pkg.dev/unicorn-985/public-images/docker-images_mysql-cloner-action:v1',
  docker_action_image: 'docker://europe-docker.pkg.dev/gynzy-test-project/public-images/push-to-gcr-github-action:v1',
  default_job_image: 'mirror.gcr.io/alpine:3.20.0',
  default_mysql8_image: 'europe-docker.pkg.dev/unicorn-985/private-images/docker-images_mysql8_utf8mb4:v1',
  default_cloudsql_image: 'europe-docker.pkg.dev/unicorn-985/private-images/docker-images_cloudsql-sidecar:v1',
  default_redis_image: 'mirror.gcr.io/redis:5.0.6',
  default_unicorns_image: 'mirror.gcr.io/node:18.15',
  default_pubsub_image: 'mirror.gcr.io/messagebird/gcloud-pubsub-emulator:latest',
  default_mongodb_image: 'europe-docker.pkg.dev/unicorn-985/private-images/docker-images_mongo6-replicated:v1',
  mongo_job_image: 'europe-docker.pkg.dev/unicorn-985/public-images/docker-images_mongo-cloner-job:v1',
  default_python_image: 'mirror.gcr.io/python:3.12.1',
  default_pulumi_node_image: 'mirror.gcr.io/node:18',
  job_poster_image: 'europe-docker.pkg.dev/unicorn-985/public-images/docker-images_job-poster:v2',
}
